name = "ReinforcementRace"
uuid = "dd04acb2-308f-11e9-02a6-3d55b75ff8e2"
authors = ["Luciano Lorenti <luciano.lorenti@jampp.com>"]
version = "0.1.0"

[deps]
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
